### ISSUE TITLE
[Server] Finir

### ISSUE THREAD

**Issue by lo23username** [LO23TD01/LO23TD01#108]
Une fois que Data et Network auront fini de coder, on merge et on teste.

**Comment by lo23username** [comment]
Note : Data est fini au niveau code. Il ne manque plus que les dépendance par rapport à Network soit codées pour que je puisse decommenter mon code.

**Comment by lo23username** [comment]
Note : Data est fini au niveau code. Il ne manque plus que les dépendances par rapport à Network soient codées pour que je puisse decommenter mon code.

**Comment by lo23username** [comment]
les Issues dont je parle : #77 #104 et #105

**Comment by ArthurPons** [comment]
#77 Fini côté server, data peut décommenter.

**Comment by lo23username** [comment]
Necessite #137 maintenant.

**Comment by lo23username** [comment]
Done en #142 
J'ai fini le serveur dessus car ma branche était inrebasable.
