### ISSUE TITLE
[Réseau] Refactoring + Ajout des appels de méthode de ClienDataEngine

### ISSUE THREAD

**Issue by mathieudi** [LO23TD01/LO23TD01#112]
- Refactoring des messages pour prendre en compte les properties (sérialisation avec fx-gson).
- Correction usage UUID dans ComServer.
- Ajout des appels de méthodes de ClientDataEngine dans les process des messages suite à la mise à disposition de l'interface par Data.

**Comment by PG-Tips** [comment]
Done
