### ISSUE TITLE
[Data - Network] Coder quatres nouvelles méthodes

### ISSUE THREAD

**Issue by lo23username** [LO23TD01/LO23TD01#137]
Pour changer le tour et l'état des tables, il nous faut quatre nouvelles méthodes.
Deux appelées par Data sur le serveur : changeState(List<UUID>, State) et changeTurnState(List<UUID>,TurnState)
AU niveau client, Data devra coder deux méthodes appellées par network du type : changeState(State) et changeTurnState(TurnState)

Je m'occupe de Data, un mec du réseau doit faire la partie Réseau

**Comment by lo23username** [comment]
J'ai fait le commit Data

**Comment by mathieudi** [comment]
Done : PR créée

**Comment by lo23username** [comment]
Done, reste à integrer.
