### ISSUE TITLE
[Data-Client] getLocalProfile

### ISSUE THREAD

**Issue by JeanDupas** [LO23TD01/LO23TD01#31]
Implémentation des méthodes getLocalProfile() et les surcharges dans l'InterfaceDataIHMLobby.

**Comment by nyashes** [comment]
@Benoit95 du nouveau sur ce truc?

**Comment by Benoit95** [comment]
Il faut que l'on en parle demain. Le ticket n'est pas encore traite.

**Comment by nyashes** [comment]
Ok

**Comment by lo23username** [comment]
Ca m'a l'air fini
