### ISSUE TITLE
[Data] Séparer Client/Serveur

### ISSUE THREAD

**Issue by JeanDupas** [LO23TD01/LO23TD01#32]
Séparation des packages client serveur : il faut séparer les data client/serveur et général. Dans le package data, on a les classes data utilisées à la fois dans serveur et client. Dans le serveur on a les classes spécifiques au serveur : ServerDataEngine, InterfaceDataNetwork par exemple. Et dans le client on a les classes spécifiques au client : les interfacesLobby, etc.

**Comment by nyashes** [comment]
@JeanDupas est-ce qu'il existe une trace indiquant ce qui doit être séparé ou bien est-ce que je le fais au feeling?

**Comment by JeanDupas** [comment]
Il faut utiliser les diagrammes de classe. On en a trois dans le dossier conception général : server, client et data général.
