### ISSUE TITLE
[Data - Server] Se deconnecter, modifer Profil, voir Profil, rafraichir UserList, Creer Table, Rejoindre Table, Commencer Partie

### ISSUE THREAD

**Issue by lo23username** [LO23TD01/LO23TD01#39]
Toutes les méthodes Data Server associées à ces diagrammes ainsi que des corrections appliquées à l'interface de Network

**Comment by lo23username** [comment]
Done :

https://github.com/LO23TD01/LO23TD01/tree/develop/klajaeti/39

**Comment by nyashes** [comment]
utilise le numéro de PR pour référencer un truc que tu viens de faire, pas un lien vers le code à l'avenir

**Comment by nyashes** [comment]
en l’occurrence j'imagine que c'est la #37 mais c'est mieux de l'expliciter
