### ISSUE TITLE
[Data]Regler le Ruleset de Regles

### ISSUE THREAD

**Issue by lo23username** [LO23TD01/LO23TD01#53]

**Comment by nyashes** [comment]
Tente de détailler les issues, par exemple en faisant référence au document permettant de savoir si le travail a bien été fait à la fin ou bien en détaillant le travail à réaliser pour terminer cette macro-tache
De plus il n'y a pas d'assignee sur cette tache alors que j'avais cru comprendre que tu bossait dessus, je te l'assigne dans le doute, tu te la retirera si je me trompe

**Comment by lo23username** [comment]
Réglé dans #79

Puisque ca influence directement le moteur de jeu, je l'ai fait avec.
Un détail des regles est en commentaire dans le Rules.java

**Comment by lo23username** [comment]
On peux fermer l'issue, c'est réglé et intégré
