### ISSUE TITLE
[Réseau] Rejoindre Table

### ISSUE THREAD

**Issue by ArthurPons** [LO23TD01/LO23TD01#58]

**Comment by nyashes** [comment]
@ArthurPons pas de description mais auto-assigné donc on passe là dessus, par contre du nouveau sur cette fonction?

**Comment by ArthurPons** [comment]
Si j'ai pas fait d'erreur c'est fini.

**Comment by nyashes** [comment]
ce truc est fait? pas de PR lié mais la dose de commit @ArthurPons @PG-Tips

**Comment by ArthurPons** [comment]
Oui c'est bon !
