### ISSUE TITLE
Ajout du controller et data pour playerStat

### ISSUE THREAD

**Issue by TheFump** [LO23TD01/LO23TD01#66]
Tout est dans le titre.

**Comment by nyashes** [comment]
seems legit. Puisque tu n'es pas le manager officiel, je le passe en request par contre.

**Comment by TheFump** [comment]
Entendu, il faut que je le fasse passer par le manager pour le valider ? 
J'ai rajouté data sur l'issue parce qu'il va falloir qu'on discute des properties cet après midi.
